### ISSUE TITLE
Running pipeline raises ValueError: PWV is out of range

### ISSUE THREAD

**Issue by djperrefort** [LSSTDESC/SN-PWV#103]
Running the fitting pipeline via the CLI raises a value error. For example:

`python fitting_cli.py -c alt_sched -s 0 -f 0 -o validation/pwv_sim_0_fit_0.csv -i 100 -p 12`

gives:

```
Traceback (most recent call last):
  File "/home/djperrefort/anaconda3/envs/SN-PWV/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/djperrefort/anaconda3/envs/SN-PWV/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/djperrefort/Github/SN-PWV/snat_sim/fitting_pipeline.py", line 287, in _duplicate_light_curves
    duplicated_lc = reference_stars.divide_ref_from_lc(duplicated_lc, pwv_los, self.reference_stars)
  File "/home/djperrefort/Github/SN-PWV/snat_sim/reference_stars.py", line 184, in divide_ref_from_lc
    table_copy['flux'][band_indices] /= average_norm_flux(band, pwv[band_indices], reference_types)
  File "/home/djperrefort/Github/SN-PWV/snat_sim/reference_stars.py", line 154, in average_norm_flux
    return np.average([interp_norm_flux(band, pwv, stype) for stype in reference_types], axis=0)
  File "/home/djperrefort/Github/SN-PWV/snat_sim/reference_stars.py", line 154, in <listcomp>
    return np.average([interp_norm_flux(band, pwv, stype) for stype in reference_types], axis=0)
  File "/home/djperrefort/Github/SN-PWV/snat_sim/reference_stars.py", line 136, in interp_norm_flux
    raise ValueError('PWV is out of range')
ValueError: PWV is out of range
```

It looks like the range of PWV values used in `data/stellar_fluxes/stellar_fluxes.py` needs to be extended.

**Comment by djperrefort** [comment]
I've been able to reproduce the error using the following gist: https://gist.github.com/djperrefort/a56958446e8512431d54ca8090481cd4
